number = 10
del number # delete number
# print(number) => error cause we have deleted this var
